### ISSUE TITLE
Can Chinese characters be supported in the path?

### ISSUE THREAD

**Issue by liu-jin-yi** [xan105/node-win-verify-trust#1]
For example, c:/人名 ....

**Comment by xan105** [comment]
If non latin paths aren't already supported then that's an oversight. I'm unavailable for a couple of days. I'll give it a look when I can.

**Comment by liu-jin-yi** [comment]
I have fixed it and submitted a PR, you can take a look. I also sent you an email

**Comment by xan105** [comment]
Published v1.5.1 with your changes

**Comment by xan105** [comment]
Published v1.5.2 with updated prebuilds. I was unable to do it sooner; sorry for any inconvenience.
